// flow-typed signature: d6804fe40eb0e1bdfcc4f609c7eb6715
// flow-typed version: <<STUB>>/find-root_v1.1.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'find-root'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'find-root' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'find-root/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'find-root/index' {
  declare module.exports: $Exports<'find-root'>;
}
declare module 'find-root/index.js' {
  declare module.exports: $Exports<'find-root'>;
}
declare module 'find-root/test/test.js' {
  declare module.exports: $Exports<'find-root/test/test'>;
}
